service:
  name: harness_service
  identifier: harness_service
  description: for Trial Project
  serviceDefinition:
    type: Kubernetes
    spec: {}
  gitOpsEnabled: false
  orgIdentifier: default
  projectIdentifier: Trial_Project
