service:
  name: harness_service
  identifier: harness_service
  description: for Trial Project
  serviceDefinition:
    type: Kubernetes
    spec:
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - spec:
                connectorRef: Docker_Hub_with_Pwd
                imagePath: library/nginx
                tag: <+input>
              identifier: nginx
              type: DockerRegistry
      manifests:
        - manifest:
            identifier: harnessK8sService
            type: K8sManifest
            spec:
              store:
                type: Github
                spec:
                  connectorRef: harnessgitconnector
                  gitFetchType: Branch
                  paths:
                    - harnesscdci-pipeline
                  repoName: harness-cdci
                  branch: main
                skipResourceVersioning: false
                enableDeclarativeRollback: false
  gitOpsEnabled: false
  orgIdentifier: default
  projectIdentifier: Trial_Project
