apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-cdci-deployment
  labels:
    app: harness-cdci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-cdci
  template:
    metadata:
      labels:
        app: harness-cdci
    spec:
      containers:
        - name: harness-cdci-deployment
          image: ronwhite562/harness-cdci
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
