apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: harness-cdci-deployment
spec:
  selector:
    # Selector for Pods
    app: harness-cdci
  ports:
    # Port Map
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
